"""Ideal reference answers for technical similarity scoring."""

IDEAL_ANSWERS: dict[str, str] = {
  "ml-001": "Supervised learning trains models on labeled input-output pairs to predict outcomes, while unsupervised learning finds patterns in unlabeled data such as clusters or latent structure.",
  "ml-002": "Bias is error from overly simple models that underfit, while variance is error from overly complex models that overfit. The tradeoff is balancing model complexity to minimize total error on unseen data.",
  "ml-003": "Overfitting happens when a model memorizes training data and performs poorly on new data. Prevent it with regularization, cross-validation, more data, simpler models, early stopping, and dropout in neural networks.",
  "ml-004": "Bagging trains many models in parallel on bootstrap samples and averages predictions to reduce variance. Boosting trains models sequentially, each correcting prior errors, to reduce bias.",
  "ml-005": "Gradient descent iteratively updates model parameters in the direction that reduces a loss function, using the gradient of the loss with respect to parameters and a learning rate.",
  "ml-006": "A decision tree splits data by choosing the feature and threshold that best separate classes or reduce impurity metrics like Gini or entropy, recursively building branches until stopping criteria are met.",
  "ml-007": "The curse of dimensionality means that as feature dimensions grow, data becomes sparse, distances become less meaningful, and models need exponentially more data to generalize well.",
  "ml-008": "Use linear regression for continuous target prediction and logistic regression for binary classification, where outputs are transformed through a sigmoid to represent probabilities.",
  "ml-009": "Cross-validation splits data into folds to train and validate on different subsets, giving a more reliable estimate of model performance and helping tune hyperparameters without leaking test data.",
  "ml-010": "Random forests are ensembles of decorrelated decision trees trained on bootstrap samples and random feature subsets, improving robustness and reducing overfitting compared to a single tree.",
  "ml-011": "K-means clustering partitions data into k groups by iteratively assigning points to the nearest centroid and updating centroids as cluster means until convergence.",
  "ml-012": "XGBoost adds regularization, parallel tree construction, handling of sparse data, and a more efficient split-finding algorithm to standard gradient boosting, often improving speed and performance.",
  "ml-013": "Regularization penalizes large coefficients to reduce overfitting. L1 promotes sparsity and feature selection, while L2 shrinks coefficients smoothly without forcing many to zero.",
  "ml-014": "A support vector machine finds the hyperplane that maximizes the margin between classes, and can use kernel tricks to model nonlinear decision boundaries in higher-dimensional space.",
  "ml-015": "PCA projects data onto orthogonal directions of maximum variance to reduce dimensionality while preserving as much information as possible, useful for visualization, compression, and noise reduction.",
  "dl-001": "A neural network is a stack of layers of interconnected neurons that learn hierarchical representations by applying weighted sums, nonlinear activations, and training via backpropagation.",
  "dl-002": "Backpropagation computes gradients of the loss with respect to each parameter using the chain rule, propagating error signals backward so optimizers can update weights.",
  "dl-003": "Vanishing gradients occur when gradients shrink as they propagate through many layers, especially with saturating activations, making early layers hard to train in deep networks.",
  "dl-004": "ReLU avoids saturation for positive inputs and trains faster. Sigmoid and tanh squash outputs into bounded ranges but can saturate and cause vanishing gradients in deep networks.",
  "dl-005": "Batch normalization standardizes layer inputs across a mini-batch, stabilizing training, allowing higher learning rates, and acting as mild regularization.",
  "dl-006": "A CNN for image classification uses convolutional layers to extract local features, pooling to reduce spatial size, and fully connected layers to map features to class probabilities.",
  "dl-007": "Dropout randomly disables neurons during training to prevent co-adaptation, forcing the network to learn redundant representations and reducing overfitting.",
  "dl-008": "An LSTM uses gates to control what information to forget, store, and output across time steps, helping capture long-range dependencies in sequential data.",
  "dl-009": "Transfer learning reuses a model pretrained on a large dataset and adapts it to a new task by fine-tuning some or all layers, saving data and training time.",
  "dl-010": "Attention lets a model weigh relevant parts of the input when producing each output, enabling transformers to capture long-range dependencies without recurrent connections.",
  "dl-011": "An epoch is one full pass through the training dataset. A batch is a subset of samples processed together. An iteration is one parameter update, usually on one batch.",
  "dl-012": "Choose a learning rate by starting with common defaults, using learning rate schedules, and tuning with validation loss curves or automated search methods.",
  "dl-013": "A GAN consists of a generator that creates synthetic samples and a discriminator that distinguishes real from fake data, trained adversarially to improve sample quality.",
  "dl-014": "Residual connections add the input of a block to its output, allowing gradients to flow directly through skip paths and enabling training of much deeper networks.",
  "dl-015": "Fine-tuning updates some or all weights of a pretrained model on task-specific data, often with a smaller learning rate for early layers and a larger one for the new head.",
  "stat-001": "Mean is the average, median is the middle value, and mode is the most frequent value. Median is robust to outliers, while mean reflects all values equally.",
  "stat-002": "A p-value measures how extreme observed results are under the null hypothesis. A small p-value suggests evidence against the null, but does not measure effect size or practical importance alone.",
  "stat-003": "Type I error is rejecting a true null hypothesis, a false positive. Type II error is failing to reject a false null hypothesis, a false negative.",
  "stat-004": "A normal distribution is bell-shaped, symmetric, and defined by mean and variance, with most values near the mean and probabilities described by the Gaussian density.",
  "stat-005": "Bayes theorem updates prior beliefs with evidence: posterior equals prior times likelihood divided by evidence, forming the basis of Bayesian inference.",
  "stat-006": "A confidence interval is a range of plausible values for a parameter at a chosen confidence level, reflecting sampling uncertainty rather than probability the parameter lies in the interval.",
  "stat-007": "Correlation measures statistical association between variables, while causation means one variable directly influences another. Correlation alone does not prove causation.",
  "stat-008": "Use a t-test for comparing means of continuous variables, and chi-square tests for categorical associations or goodness-of-fit comparisons.",
  "stat-009": "The central limit theorem says the sampling distribution of the mean approaches normality as sample size grows, even if the original population is not normal.",
  "stat-010": "Maximum likelihood estimation chooses parameter values that maximize the probability of observing the given data under a specified model.",
  "stat-011": "Multicollinearity occurs when predictor variables are highly correlated, making coefficient estimates unstable and harder to interpret individually.",
  "stat-012": "A/B testing randomly assigns users to control and treatment groups, compares outcomes with predefined metrics, and uses statistical tests to assess whether differences are significant.",
  "py-001": "Lists are mutable ordered sequences, while tuples are immutable ordered sequences. Tuples are often used for fixed collections and can be dictionary keys.",
  "py-002": "A pandas Series is a one-dimensional labeled array, while a DataFrame is a two-dimensional table of columns that can have different dtypes but shared index.",
  "py-003": "Handle missing values by dropping rows or columns, imputing with mean, median, mode, or model-based methods, or creating indicator features depending on missingness mechanism.",
  "py-004": "Vectorization applies operations to entire arrays in compiled code instead of Python loops, greatly improving performance on numerical workloads.",
  "py-005": "Groupby splits data by keys, applies aggregations or transformations to each group, and combines results, enabling summary statistics by category.",
  "py-006": "Merge joins DataFrames on keys like SQL joins, while concat stacks DataFrames along rows or columns without key-based alignment.",
  "py-007": "Read large CSVs in chunks with pandas read_csv chunksize, use dtype optimization, categorical columns, or distributed tools like Dask or PySpark when data exceeds memory.",
  "py-008": "List comprehensions provide a concise syntax to create lists by iterating over an iterable and optionally applying a filter or transformation.",
  "py-009": "NumPy broadcasting applies arithmetic between arrays of different shapes by virtually expanding dimensions according to compatibility rules, avoiding explicit loops.",
  "py-010": "An iterator produces values one at a time via __next__, while a generator is a special iterator defined with yield that lazily generates a sequence.",
  "py-011": "Optimize Python data code with vectorization, efficient dtypes, avoiding unnecessary copies, profiling bottlenecks, and using libraries like NumPy, pandas, or Polars.",
  "py-012": "The Global Interpreter Lock allows only one thread to execute Python bytecode at a time in CPython, limiting CPU-bound parallelism but not necessarily I/O-bound concurrency.",
  "fe-001": "One-hot encoding converts categorical values into binary indicator columns, one per category, avoiding false ordinal relationships between labels.",
  "fe-002": "Use one-hot for nominal categories with few unique values and label encoding for ordinal categories or tree models that can handle integer-coded categories.",
  "fe-003": "Normalization scales values to a fixed range like 0 to 1, while standardization centers data to zero mean and unit variance. Choice depends on algorithm sensitivity.",
  "fe-004": "Feature selection reduces dimensionality, improves interpretability, lowers overfitting risk, and can speed training by keeping only informative predictors.",
  "fe-005": "For high-cardinality categoricals, use target encoding, hashing, embeddings, grouping rare categories, or models that handle large categorical spaces efficiently.",
  "fe-006": "Target encoding replaces a category with a statistic of the target variable for that category, often with regularization to prevent leakage and overfitting.",
  "fe-007": "Polynomial features create interaction and higher-order terms from original features, allowing linear models to capture nonlinear relationships.",
  "fe-008": "Create time-based features such as hour, day of week, month, lag variables, rolling averages, and time since last event to capture seasonality and trends.",
  "fe-009": "Feature importance in tree models measures how much each feature reduces impurity or loss across splits, indicating relative predictive contribution.",
  "fe-010": "Handle imbalance with resampling, class weights, appropriate metrics like F1 or AUC, anomaly detection framing, or synthetic oversampling methods such as SMOTE.",
  "eval-001": "Accuracy is the fraction of correct predictions. It is misleading on imbalanced datasets because a majority-class classifier can look accurate while failing on minorities.",
  "eval-002": "Precision is true positives divided by predicted positives, recall is true positives divided by actual positives, and F1 is their harmonic mean balancing both.",
  "eval-003": "ROC-AUC measures how well a classifier ranks positives above negatives across thresholds, summarizing tradeoffs between true positive rate and false positive rate.",
  "eval-004": "A confusion matrix tabulates true positives, false positives, true negatives, and false negatives, forming the basis for many classification metrics.",
  "eval-005": "RMSE penalizes large errors more due to squaring, while MAE measures average absolute error and is more robust to outliers.",
  "eval-006": "Detect data leakage by ensuring preprocessing and feature engineering use only training data, avoiding future information, duplicate target proxies, and improper cross-validation.",
  "eval-007": "Stratified k-fold cross-validation preserves class proportions in each fold, giving more reliable performance estimates for classification with imbalanced classes.",
  "eval-008": "Calibration means predicted probabilities match observed frequencies. A well-calibrated model's 70 percent predictions should be correct about 70 percent of the time.",
  "eval-009": "A learning curve plots training and validation performance against dataset size or training iterations to diagnose bias, variance, and data sufficiency.",
  "eval-010": "Compare models statistically with paired tests on cross-validation scores, confidence intervals, or bootstrap comparisons rather than relying on a single metric difference.",
  "nlp-001": "Tokenization splits text into tokens such as words or subwords, forming the first step for most NLP pipelines and model input preparation.",
  "nlp-002": "TF-IDF weights terms by term frequency in a document and inverse document frequency across the corpus, highlighting distinctive words and downweighting common ones.",
  "nlp-003": "Word embeddings are dense vector representations that capture semantic relationships, placing similar words closer together in vector space.",
  "nlp-004": "Word2Vec learns embeddings by predicting context words from a target word in skip-gram or predicting a target from context in CBOW using shallow neural networks.",
  "nlp-005": "BERT is a transformer pretrained with masked language modeling and next sentence prediction, producing contextual embeddings effective for many downstream NLP tasks.",
  "nlp-006": "Named entity recognition identifies and classifies entities such as people, organizations, and locations in text.",
  "nlp-007": "Sentiment analysis determines whether text expresses positive, negative, or neutral opinion, often using classification models or lexicon-based methods.",
  "nlp-008": "Handle out-of-vocabulary words with subword tokenization, character models, unknown token strategies, or pretrained vocabularies that reduce unseen tokens.",
  "nlp-009": "BLEU score measures n-gram overlap between generated and reference text, commonly used to evaluate machine translation and text generation quality.",
  "nlp-010": "Sequence-to-sequence models encode an input sequence into a representation and decode an output sequence, often with attention for tasks like translation and summarization.",
  "cv-001": "Image classification assigns one label to an entire image, while object detection localizes and classifies multiple objects with bounding boxes.",
  "cv-002": "Convolution slides learnable filters across an image to detect local patterns such as edges and textures while sharing weights across spatial locations.",
  "cv-003": "Pooling reduces spatial dimensions by aggregating local regions, commonly with max or average pooling, improving translation invariance and computational efficiency.",
  "cv-004": "Data augmentation artificially expands training data with transformations like flips, crops, and color jitter, improving generalization and reducing overfitting.",
  "cv-005": "Intersection over Union measures overlap between predicted and ground-truth boxes, used to judge detection quality and non-maximum suppression thresholds.",
  "cv-006": "YOLO treats detection as a single regression problem, dividing the image into a grid and predicting bounding boxes and class probabilities in one forward pass.",
  "cv-007": "Semantic segmentation assigns a class label to every pixel, distinguishing objects at pixel level rather than with bounding boxes alone.",
  "cv-008": "Handle class imbalance with weighted loss, oversampling rare classes, focal loss, careful augmentation, and metrics that reflect minority class performance.",
  "cv-009": "Transfer learning in vision uses pretrained CNNs on large datasets like ImageNet and fine-tunes them on smaller target datasets to improve accuracy with less data.",
  "cv-010": "Non-maximum suppression removes redundant overlapping detections by keeping the highest-confidence box and suppressing others with high IoU overlap.",
  "ops-001": "MLOps applies DevOps practices to machine learning, covering reproducible training, deployment, monitoring, and continuous improvement of models in production.",
  "ops-002": "Model versioning tracks trained artifacts, code, data snapshots, and hyperparameters so experiments and deployments can be reproduced and rolled back.",
  "ops-003": "Model drift is degradation in model performance over time due to changes in input data distribution or relationships between features and target.",
  "ops-004": "Containerize an ML model by packaging the inference code, dependencies, and serialized model into a Docker image for consistent deployment across environments.",
  "ops-005": "CI/CD for machine learning automates testing, training, validation, and deployment pipelines so model updates are reliable and repeatable.",
  "ops-006": "A feature store is a centralized system for defining, storing, and serving consistent features for both training and online inference.",
  "ops-007": "Monitor production models with latency, throughput, data drift, prediction drift, error rates, and business KPIs, triggering retraining when thresholds are breached.",
  "ops-008": "A/B testing for ML models routes traffic between model versions and compares business or performance metrics to decide which model should be promoted.",
  "sql-001": "INNER JOIN returns only matching rows from both tables, while LEFT JOIN returns all rows from the left table and matched rows from the right, with nulls where no match exists.",
  "sql-002": "GROUP BY aggregates rows with the same key values, while HAVING filters groups after aggregation, similar to WHERE but for grouped results.",
  "sql-003": "A window function performs calculations across a set of rows related to the current row without collapsing them into a single grouped output.",
  "sql-004": "Find duplicates by grouping on key columns and using HAVING COUNT greater than 1, or by window functions like ROW_NUMBER to identify repeated records.",
  "sql-005": "Indexes speed up lookups and joins on indexed columns but add storage and write overhead, so they help selective queries more than full table scans.",
  "sql-006": "Normalization reduces redundancy by splitting data into related tables, while denormalization duplicates data to improve read performance at the cost of consistency complexity.",
  "sql-007": "Running totals can be computed with window functions such as SUM(amount) OVER (ORDER BY date ROWS UNBOUNDED PRECEDING).",
  "sql-008": "OLTP systems handle transactional day-to-day operations with many short writes, while OLAP systems support analytical queries and aggregations over large historical datasets.",
}
